# Generated by Django 5.0.3 on 2024-04-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='bill_evans2.jpg', upload_to=''),
        ),
    ]
