# Generated by Django 5.0.3 on 2024-04-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_message',
            name='subject',
            field=models.CharField(default='music', max_length=255),
        ),
    ]
