# Generated by Django 5.0.3 on 2024-04-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
