# Generated by Django 5.0.3 on 2024-03-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('legend', models.BooleanField(default=False)),
                ('main_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=255)),
                ('video_file', models.FileField(null=True, upload_to='media/video')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.musician')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('audio_file', models.FileField(null=True, upload_to='media/audio/')),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.musician')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.musician')),
                ('perfomances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.performance')),
                ('tracks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.track')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.track'),
        ),
    ]
