# Generated by Django 5.0.3 on 2024-03-21 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_perfomances_alter_post_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='perfomances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.performance'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tracks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.track'),
        ),
    ]
