# Generated by Django 5.0.3 on 2024-03-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_performance_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='perfomances',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tracks',
        ),
        migrations.AddField(
            model_name='performance',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post'),
        ),
        migrations.AddField(
            model_name='track',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post'),
        ),
    ]
