# Generated by Django 5.0.3 on 2024-03-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_perfomances_remove_post_tracks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(default='D:/Programming/Start_Web_Programming_CS50/maz_music/media/Lilac.mp3', upload_to=''),
        ),
    ]
