# Generated by Django 5.0.3 on 2024-03-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_track_audio_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrument',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='main_instrument',
            new_name='category',
        ),
    ]
