# Generated by Django 5.0.3 on 2024-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='category',
        ),
        migrations.AddField(
            model_name='musician',
            name='category',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
