# Generated by Django 5.0.3 on 2024-03-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_musician_category_musician_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
