# Generated by Django 5.0.3 on 2024-03-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment_reply_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_post',
            new_name='post',
        ),
    ]
