# Generated by Django 5.0.3 on 2024-03-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_date']},
        ),
    ]
