# Generated by Django 5.0.3 on 2024-03-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_comment_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='musician',
        ),
        migrations.RemoveField(
            model_name='track',
            name='musician',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
