# Generated by Django 5.0.3 on 2024-03-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
