# Generated by Django 5.0.3 on 2024-04-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_delete_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply_comment',
            name='reply_comment',
        ),
        migrations.RemoveField(
            model_name='reply_comment',
            name='replier_name',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply_comment',
        ),
    ]
