# Generated by Django 5.0.3 on 2024-04-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_reply_comment_reply_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='counted_views',
        ),
    ]
